### ISSUE TITLE
Update to Laravel 11

### ISSUE THREAD

**Issue by markc** [guillaumebriday/laravel-blog#159]
Is there any chance or hints on how to update this project for Laravel 11?

**Comment by guillaumebriday** [comment]
I’d like to do it as soon as I have some time!

But if you want to start a PR, feel free to open it! 🙏

**Comment by markc** [comment]
I'd love to, but I don't know where to start. I'm a total Laravel beginner and hoping to learn from this and other projects, but it's hard to find something practical that works with Laravel 11. Good to know you are responsive to the idea, so if I do make any progress I'll certainly send a PR.

**Comment by guillaumebriday** [comment]
Done here https://github.com/guillaumebriday/laravel-blog/commit/6621a9f783b3e2122e3485b40d0921d33c2c120d

Thanks

**Comment by markc** [comment]
Thank you guillaumebriday! Even though I've been an avid GH user for over a decade I'm still not used to submitting PRs to other projects so until I RTFM, again, here's my initial suggestion in README.md (drop the $ so this section can be posted directly into a shell)...
```
git clone https://github.com/guillaumebriday/laravel-blog.git
cd laravel-blog
composer install
npm install
cp .env.example .env
touch database/database.sqlite
php artisan key:generate
php artisan storage:link
php artisan horizon:install
php artisan telescope:install
composer require laravel/pail
php artisan migrate:fresh --seed
composer run dev
```
and, in composer.json...
```
    "scripts": {
    ...
        ],
        "dev": [
            "Composer\\Config::disableProcessTimeout",
            "npx concurrently -k -c \"#93c5fd,#c4b5fd,#d4d4d8,#fdba74\" \"php artisan serve\" \"php artisan queue:listen --tries=1 --timeout=120\" \"php artisan pail\" \"npm run dev\" --names=server,queue,logs,vite"
        ]
    },
```
